export const NAV_ITEMS = [
  {
    label: "Services",
    key: "services",
    sub: [
      {
        label: "Search & Growth Strategy",
        imgSrc: "/image/Navigation/services/services-1.webp",
      },
      {
        label: "Onsite SEO",
        imgSrc: "/image/Navigation/services/services-2.webp",
      },
      {
        label: "Content Experience",
        imgSrc: "/image/Navigation/services/services-3.webp",
      },
      {
        label: "B2B Marketing",
        imgSrc: "/image/Navigation/services/services-4.webp",
      },
      {
        label: "Digital PR",
        imgSrc: "/image/Navigation/services/services-5.webp",
      },
      {
        label: "Social Media & Campaigns",
        imgSrc: "/image/Navigation/services/services-6.webp",
      },
      {
        label: "Data & Insights",
        imgSrc: "/image/Navigation/services/services-7.webp",
      },
      {
        label: "Social SEO/Search",
        imgSrc: "/image/Navigation/services/services-8.webp",
      },
    ],
    dropdownLabel: "Core Services",
    ctaLabel: "View All Services",
    imgAlt: "The Rise Services",
    imgSrc: "/image/Navigation/services/services-1.webp", // default/fallback image
  },
  {
    label: "Industries",
    key: "industries",
    sub: [
      {
        label: "B2B Marketing",
        imgSrc: "/image/Navigation/services/services-4.webp",
      },
    ],
    dropdownLabel: "Industries We Serve",
    ctaLabel: "",
    imgAlt: "Industries",
    imgSrc: "/image/Navigation/services/services-4.webp",
  },
  {
    label: "International",
    key: "international",
    sub: [
      {
        label: "US Digital PR",
        imgSrc: "/image/Navigation/international/international-2.webp",
      },
      {
        label: "Spain Digital PR",
        imgSrc: "/image/Navigation/international/international-1.webp",
      },
      {
        label: "Germany Digital PR",
        imgSrc: "/image/Navigation/international/international-3.webp",
      },
      {
        label: "Netherlands Digital PR",
        imgSrc: "/image/Navigation/international/international-4.webp",
      },
    ],
    dropdownLabel: "Global Reach",
    ctaLabel: "",
    imgAlt: "International",
    imgSrc: "/image/Navigation/international/international-3.webp",
  },
  {
    label: "About",
    key: "about",
    sub: [
      {
        label: "About Us",
        imgSrc: "/image/Navigation/about/about-2.webp",
      },
      {
        label: "Meet The Risers",
        imgSrc: "/image/Navigation/about/about-4.webp",
      },
      { label: "Culture", imgSrc: "/image/Navigation/about/about-3.webp" },
      {
        label: "Testimonials",
        imgSrc: "/image/Navigation/about/about-1.webp",
      },
    ],
    dropdownLabel: "About Rise at Seven",
    ctaLabel: "",
    imgAlt: "About the team",
    imgSrc: "/image/Navigation/about/about-2.webp",
  },
  { label: "Work", key: "work", badge: "25" },
  { label: "Careers", key: "careers" },
  {
    label: "Blog & Resources",
    key: "blog",
    sub: [
      { label: "Blog", imgSrc: "/image/Navigation/blog/blog-1.webp" },
      {
        label: "Category Leaderboard",
        imgSrc: "/image/Navigation/blog/blog-2.webp",
      },
      {
        label: "Multi Channel Search Report",
        imgSrc: "/image/Navigation/blog/blog-3.webp",
      },
    ],
    imgSrc: "/image/Navigation/blog/blog-3.webp",
  },
  { label: "Webinar", key: "webinar" },
];
export const heroIconsBottom = [
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-02.webp",
    alt: "Google Icon",
    width: 90,
    height: 90,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-03.webp",
    alt: "ChatGPT Icon",
    width: 90,
    height: 90,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-04.webp",
    alt: "Gemmini Icon",
    width: 90,
    height: 90,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-05.webp",
    alt: "Tiktok Icon",
    width: 90,
    height: 90,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-06.webp",
    alt: "youtube Icon",
    width: 90,
    height: 90,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-07.webp",
    alt: "Pinterest Icon",
    width: 90,
    height: 90,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-08.webp",
    alt: "Gifi Icon",
    width: 90,
    height: 90,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-09.webp",
    alt: "Reddit Icon",
    width: 90,
    height: 90,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-10.webp",
    alt: "amazone Icon",
    width: 70,
    height: 70,
    quality: 90,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
];

export const heroMainImage = [
  {
    src: "/image/Hero/HeroFrontBack-1.jpg",
    alt: "Google Icon",
    width: 100,
    height: 100,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/HeroFrontBack-2.jpg",
    alt: "Google Icon",
    width: 100,
    height: 100,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/HeroFrontBack-3.webp",
    alt: "Google Icon",
    width: 100,
    height: 100,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/HeroFrontBack-4.png",
    alt: "Google Icon",
    width: 100,
    height: 100,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/HeroFrontBack-5.jpg",
    alt: "Google Icon",
    width: 100,
    height: 100,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/HeroFrontBack-6.webp",
    alt: "Google Icon",
    width: 100,
    height: 100,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
];

export const projects = [
  {
    title: "SIXT",
    img: "/image/FeaturedWork/FeaturedWork-02.webp",
    imgHoverColor: "#CB7B3A",
    imgHoverText: "An extra 3m clicks regionally through SEO",
    bottomRightDesignText: "Car rental",
  },
  {
    title: "Dojo - B2B",
    img: "/image/FeaturedWork/FeaturedWork-03.webp",
    imgHoverColor: "#FDD8C4",
    imgHoverText: "A B2B success story for Dojo card machines",
    bottomRightDesignText: "Card Machines",
  },
  {
    title: "Magnet Trade - B2B",
    img: "/image/FeaturedWork/FeaturedWork-04.webp",
    imgHoverColor: "#D8C4FD",
    imgHoverText: "A full service SEO success story 170%+ increase",
    bottomRightDesignText: "",
  },
  {
    title: "Leading E Sim brand globally",
    img: "/image/FeaturedWork/FeaturedWork-05.webp",
    imgHoverColor: "#CB7B3A",
    imgHoverText: "Increasing brand and non brand visibility UK/ES",
    bottomRightDesignText: "Esims",
  },
  {
    title: "JD Sports",
    img: "/image/FeaturedWork/FeaturedWork-06.webp",
    imgHoverColor: "#3A8CCB",
    imgHoverText: "65% up YoY in clicks for JDSports FR, IT, ES",
    bottomRightDesignText: "Trainers",
  },
  {
    title: "Parkdean Resorts",
    img: "/image/FeaturedWork/FeaturedWork-07.webp",
    imgHoverColor: "#D2B59D",
    imgHoverText: "Dominating Google and AI search",
    bottomRightDesignText: "Easter Breaks",
  },
  {
    title: "Pooky",
    img: "/image/FeaturedWork/FeaturedWork-12.webp",
    imgHoverColor: "#39B0BD",
    imgHoverText: "Driving demand for Pooky Rechargeable Lights",
    bottomRightDesignText: "Rechargeable Lights",
  },
  {
    title: "Parkdean Resorts",
    img: "/image/FeaturedWork/FeaturedWork-08.webp",
    imgHoverColor: "#D29DD0",
    imgHoverText: "Social search and multi channel content to #1",
    bottomRightDesignText: "UK holidays",
  },
  {
    title: "Revolution Beauty",
    img: "/image/FeaturedWork/FeaturedWork-09.webp",
    imgHoverColor: "#FECACC",
    imgHoverText: "Building the UK's leading beauty dupe brand",
    bottomRightDesignText: "Beauty Dupes",
  },
  {
    title: "Lioyds Pharmacy",
    img: "/image/FeaturedWork/FeaturedWork-10.webp",
    imgHoverColor: "#60DCFB",
    imgHoverText: "Driving category leadership for STI tests",
    bottomRightDesignText: "STI tests",
  },
  {
    title: "PrettyLittleThing",
    img: "/image/FeaturedWork/FeaturedWork-11.webp",
    imgHoverColor: "#FECACC",
    imgHoverText: 'Driving discovery for everything "outfits" for PLT',
    bottomRightDesignText: "Outfits",
  },
];
