export const NAV_ITEMS = [
  {
    label: "Services",
    key: "services",
    sub: [
      "Search & Growth Strategy",
      "Onsite SEO",
      "Content Experience",
      "B2B Marketing",
      "Digital PR",
      "Social Media & Campaigns",
      "Data & Insights",
      "Social SEO/Search",
    ],
    dropdownLabel: "Core Services",
    ctaLabel: "View All Services",
    imgAlt: "The Rise Lounge",

    imgSrc: "/images/rise-lounge.jpg",
  },
  {
    label: "Industries",
    key: "industries",
    sub: ["B2B Marketing"],
    dropdownLabel: "Industries We Serve",
    ctaLabel: "View All Industries",
    imgAlt: "Industries",
    imgSrc: "/images/industries.jpg",
  },
  {
    label: "International",
    key: "international",
    sub: [
      "US Digital PR",
      "Spain Digital PR",
      "Germany Digital PR",
      "Netherlands Digital PR",
    ],
    dropdownLabel: "Global Reach",
    ctaLabel: "Go Global",
    imgAlt: "International",
    imgSrc: "/images/international.jpg",
  },
  {
    label: "About",
    key: "about",
    sub: ["About Us", "Meet The Risers", "Culture", "Testimonials"],
    dropdownLabel: "About Rise at Seven",
    ctaLabel: "Learn More",
    imgAlt: "The Team",
    imgSrc: "/images/team.jpg",
  },
  { label: "Work", key: "work", badge: "25" },
  { label: "Careers", key: "careers" },
  {
    label: "Blog & Resources",
    key: "blog",
    sub: ["Blog", "Category Leaderboard", "Multi Channel Search Report"],
  },
  { label: "Webinar", key: "webinar" },
];

export const heroIconsBottom = [
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-02.webp",
    alt: "Google Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-03.webp",
    alt: "ChatGPT Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-04.webp",
    alt: "Gemmini Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-05.webp",
    alt: "Tiktok Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-06.webp",
    alt: "youtube Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-07.webp",
    alt: "Pinterest Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-08.webp",
    alt: "Gifi Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-09.webp",
    alt: "Reddit Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
  {
    src: "/image/Hero/heroFrontIcon/HeroFront-Icon-10.webp",
    alt: "amazone Icon",
    width: 150,
    height: 150,
    quality: 100,
    placeholder: "blur",
    shimmer: `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2U1ZTdlYiIvPjwvc3ZnPg==`,
  },
];
