export const NAV_ITEMS = [
  {
    label: "Services",
    key: "services",
    sub: [
      "Search & Growth Strategy",
      "Onsite SEO",
      "Content Experience",
      "B2B Marketing",
      "Digital PR",
      "Social Media & Campaigns",
      "Data & Insights",
      "Social SEO/Search",
    ],
    dropdownLabel: "Core Services",
    ctaLabel: "View All Services",
    imgAlt: "The Rise Lounge",
    // swap src with your real image path
    imgSrc: "/images/rise-lounge.jpg",
  },
  {
    label: "Industries",
    key: "industries",
    sub: ["B2B Marketing"],
    dropdownLabel: "Industries We Serve",
    ctaLabel: "View All Industries",
    imgAlt: "Industries",
    imgSrc: "/images/industries.jpg",
  },
  {
    label: "International",
    key: "international",
    sub: [
      "US Digital PR",
      "Spain Digital PR",
      "Germany Digital PR",
      "Netherlands Digital PR",
    ],
    dropdownLabel: "Global Reach",
    ctaLabel: "Go Global",
    imgAlt: "International",
    imgSrc: "/images/international.jpg",
  },
  {
    label: "About",
    key: "about",
    sub: ["About Us", "Meet The Risers", "Culture", "Testimonials"],
    dropdownLabel: "About Rise at Seven",
    ctaLabel: "Learn More",
    imgAlt: "The Team",
    imgSrc: "/images/team.jpg",
  },
  { label: "Work", key: "work" },
  { label: "Careers", key: "careers" },
  {
    label: "Blog & Resources",
    key: "blog",
    sub: ["Blog", "Category Leaderboard", "Multi Channel Search Report"],
    badge: "25",
  },
  { label: "Webinar", key: "webinar" },
];
